clickhouse_ftw:
  target: remote
  outputs:
    local:
      type: clickhouse
      host: clickhouse
      port: 8123
      user: ftw_user
      password: ftw_pass
      schema: mart        # ✅ dbt will write into mart
      threads: 4
      secure: false

    remote:
      type: clickhouse
      host: 54.87.106.52
      port: 8123
      user: ftw_user
      password: ftw_pass
      schema: mart      
      threads: 4
      secure: false
